language: php

matrix:
  include:
  - php: 5.6
  - php: 7.1
  - php: 7.2
  - php: nightly

  fast_finish: true

  allow_failures:
  - php: nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist
  - ulimit -c unlimited || true

script:
  - echo "no tests implemented"

deploy:
    provider: script
    script: scripts/deploy.sh
    skip_cleanup: false
    on:
      tags: true
      condition: "$TRAVIS_PHP_VERSION = 5.6"

notifications:
    slack: crazyfactory:Z3NJKlj5jdPOE1YrjPPyDPKb